version: '3.8'

services:
  php-apache:
    build: 
      context: .   
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - /root/htdocs/mvc_app_php:/var/www/html
    networks:
      - server

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Secretpassword"      # Contrase침a para el usuario root
      MYSQL_DATABASE: "php_app"                  # Base de datos que se crear치
      MYSQL_USER: "php_app"                     # Usuario adicional que se crear치
      MYSQL_PASSWORD: "php_app"             # Contrase침a para el usuario adicional
    volumes:
      - /root/htdocs/db:/var/lib/mysql
    networks:
      - server

networks:
  server:
    driver: bridge
